'use server';

/**
 * @fileOverview AI Legal Document Generator.
 *
 * - generateLegalDocument - A function that handles legal document generation.
 * - GenerateLegalDocumentInput - The input type for the generateLegalDocument function.
 * - GenerateLegalDocumentOutput - The return type for the generateLegalDocument function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateLegalDocumentInputSchema = z.object({
  companyName: z.string().describe('The name of the company or website.'),
  websiteUrl: z.string().url().describe('The full URL of the website.'),
  niche: z.string().describe('The niche or industry of the website (e.g., e-commerce, blog, SaaS).'),
  country: z.string().describe('The primary country of operation (e.g., USA, Canada, UK).'),
  documentType: z.enum(['Privacy Policy', 'Terms of Service']).describe('The type of legal document to generate.'),
});
export type GenerateLegalDocumentInput = z.infer<typeof GenerateLegalDocumentInputSchema>;

const GenerateLegalDocumentOutputSchema = z.object({
  document: z.string().describe('The full text of the generated legal document.'),
});
export type GenerateLegalDocumentOutput = z.infer<typeof GenerateLegalDocumentOutputSchema>;

export async function generateLegalDocument(input: GenerateLegalDocumentInput): Promise<GenerateLegalDocumentOutput> {
  return generateLegalDocumentFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateLegalDocumentPrompt',
  input: {schema: GenerateLegalDocumentInputSchema},
  output: {schema: GenerateLegalDocumentOutputSchema},
  prompt: `You are an AI assistant designed to help generate legal documents for websites. You are not a lawyer and the output is not legal advice. Always include a disclaimer to consult a legal professional.

Generate a comprehensive {{documentType}} for a website with the following details:

- **Company Name / Website Name:** {{{companyName}}}
- **Website URL:** {{{websiteUrl}}}
- **Niche / Industry:** {{{niche}}}
- **Country of Operation:** {{{country}}}

The generated document should be well-structured with clear headings and cover standard clauses appropriate for a {{documentType}} for this type of website and jurisdiction.

**Important Instructions:**
1.  Start the document with a clear title: "{{documentType}} for {{{companyName}}}".
2.  Include a "Last Updated" date.
3.  Structure the document with numbered headings (e.g., 1. Introduction, 2. Information We Collect, etc.).
4.  At the very end of the document, include the following disclaimer, clearly separated from the rest of the text:
    "**Disclaimer:** This document was generated by an AI assistant. It is for informational purposes only and does not constitute legal advice. You should consult with a qualified legal professional to ensure compliance with all applicable laws and regulations."

Please generate the full text of the {{documentType}}.
`,
});

const generateLegalDocumentFlow = ai.defineFlow(
  {
    name: 'generateLegalDocumentFlow',
    inputSchema: GenerateLegalDocumentInputSchema,
    outputSchema: GenerateLegalDocumentOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
